### ISSUE TITLE
Setup golangci-lint for all golang projects

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#689]
As request in https://github.com/anuvu/zot/issues/206#issuecomment-885133949

**Comment by burntcarrot** [comment]
I would like to take this issue but I apologize for taking up such a small issue again, because I'm new to go-storage and the codebase is enormous. I've been trying to understand each component since weeks, but I've been unable to do so, due to my lesser expertise in storage solutions. Hopefully I'll understand storage solutions in a better way one day. ♥

The only contributions I can currently make are CI setups and issues labeled with `area/engineering`. Apologies once again. 😓

**Comment by burntcarrot** [comment]
On a side note, more docs for each service and its internal components would be preferred! 😀

**Comment by Xuanwo** [comment]
> On a side note, more docs for each service and its internal components would be preferred! grinning

It's indeed a problem. Can you start a new issue to describe which part you can't understand most in `go-storage` or `go-service-*`? We are happy to help!
